config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resources :categories, except: :destroy

  resources :posts, except: :destroy do
    member do
      post 'vote'
    end

    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end
  end

  resources :users, only: [:show, :create, :edit, :update]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories, dependent: :destroy
  has_many :posts , through: :post_categories

  validates :name, presence: true, uniqueness: true

  include Sluggable
  sluggable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  belongs_to :post

  validates :body, presence: true

  include Voteable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :comments, dependent: :destroy
  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  include Voteable
  include Sluggable
  sluggable_column :title
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  
  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true, length: {maximum: 27}
  validates :password, presence: true, on: :create, length: {minimum: 5, maximum: 50}

  include Sluggable
  sluggable_column :username

  def admin?
    self.role == 'admin'
  end

  def moderator?
    self.role == 'moderator'
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: :voteable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to do that."
      redirect_to root_path
    end
  end

  def require_admin
    access_denied unless logged_in? && current_user.admin?
  end
  
  def access_denied
    flash[:error] = 'You do not have permission to do that.'
    redirect_to root_path
  end
end

app/controllers/categories.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)  
    @category.name = @category.name.downcase

    if @category.save
      flash[:notice] = "A new category was created."
      redirect_to categories_path
    else
      render :new 
    end
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end

  private

  def category_params
    params.require(:category).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create
    @post = Post.find_by slug: params[:post_id]

    @comment = @post.comments.new(comment_params)

    @comment.creator = current_user

    if @comment.save
      flash[:notice] = 'Your comment was added.'
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    existing_votes = @comment.votes.where(user_id: current_user.id)
    if existing_votes.empty?
      Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])
    else
      existing_votes.first.update(vote: params[:vote])
    end

    @upvote = params[:vote]
    
    respond_to do |format|
      format.html do
        redirect_back fallback_location: root_path
      end
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator_or_admin, only: [:edit, :update] 

  def index
    @posts = Post.all.sort_by {|post| post.created_at}
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = 'Your post was created.'
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = 'This post was updated.'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    # there should be at most 1 element in the array because we enforce
    # uniqueness of user-voteable
    existing_votes = @post.votes.where(user_id: current_user.id)
    if existing_votes.empty?
      Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    else
      existing_votes.first.update(vote: params[:vote])
    end

    @upvote = params[:vote]

    respond_to do |format|
      format.html do
        redirect_back fallback_location: root_path
      end
      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def require_creator_or_admin
    access_denied unless logged_in? && (current_user == @post.creator || current_user.admin?)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you've logged in."
      redirect_to root_path
    else
      flash.now[:error] = "There is something wrong with your username or password."
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
  
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'You are registered.'
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Your profile was updated.'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :time_zone)  
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def require_same_user
    access_denied unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.start_with?('http://', 'https://') ? str : "http://#{str}"
  end

  def display_datetime(dt)
    if logged_in? && !current_user.time_zone.blank?
      dt = dt.in_time_zone(current_user.time_zone)
    end
    dt.strftime("%m/%d/%Y %l:%M%P %Z")
  end

  def restrict_newlines(text, n)
    text.count("\n") > n ? text.split("\n")[0..n].join("\n") + "..." : text
  end
end

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<section class='container'>
  <%= form_with(model: @category, local: true, html: {autocomplete: 'off'}) do |f| %>
    <div class='form-group'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control w-50' %>
    </div>
    <%= f.submit(options={class: "btn btn-outline-primary mt-3"}) %>
  <% end %>
</section>

app/views/categories/index.html.erb
<%= render 'shared/header', title: "Categories" %>

<ul>
<% @categories.each do |category| %>
  <li><%= link_to(category.name.capitalize + " (#{pluralize(category.posts.size, 'post')})", category) %></li>
<% end %>
</ul>

app/views/categories/new.html.erb
<%= render 'shared/header', title: "Create a new category" %>
<%= render 'form' %>

app/views/categories/show.html.erb
<% title = "Posts Tagged \"#{@category.name.capitalize}\"" %>
<%= render 'shared/header', title: title %>

<% posts = @category.posts %>
<section class="row justify-content-center"> 
  <% if posts.empty? %>
    No posts to show.
  <% else %>
    <% posts.each_with_index do |post, i| %>
      <%= render 'posts/post', post: post %>
    <% end %>
  <%end %>
</section>

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<article class="card bg-light mb-3" style="max-width: 18rem;">
  <div class='row no-gutters h-100'>
    <aside class='col-md-2 votes text-center'>
      <%= render 'shared/vote', obj: comment %>
    </aside>

    <section class='col-md-10'>
      <main class="card-body">
        <p class="card-text"><%= comment.body %></p>
      </main>

        <footer class='card-footer'>
        <small class='text-muted'>
        <% if show_post %>
          <%= link_to comment.post.title, post_path(comment.post) %>
        <% end %>
        </small>
        <%= render 'shared/creator_details', obj: comment %>
        </footer>
  </div>
</article>

app/views/comments/vote.js.erb
$total_votes = $('#<%= @comment.class %>_<%= @comment.id %>_votes');
$total_votes.text(<%= @comment.total_votes %>);
$upvote = $total_votes.siblings('.upvote');
$downvote = $total_votes.siblings('.downvote');

if (<%= @upvote %>) {
  $upvote.html('<i><i class="fas fa fa-arrow-up disabled"></i>');
  $downvote.html('<%= link_to(vote_post_comment_path(@comment, vote: false), method: 'post', remote: true) {|x| fa_icon 'arrow-down'} %>');
} else {
  $downvote.html('<i><i class="fas fa fa-arrow-down disabled"></i>');
  $upvote.html('<%= link_to(vote_post_comment_path(@comment, vote: true), method: 'post', remote: true) {|x| fa_icon 'arrow-up'} %>');
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Postit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>
<section class='container'>
  <%= form_with(model: @post, local: true, html: {autocomplete: 'off'}) do |f| %>
    <div class='form-group'>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control w-50' %>
    </div>
    <div class='form-group'>
      <%= f.label :url, 'URL' %>
      <%= f.text_field :url, class: 'form-control w-50' %>
    </div>
    <div class='form-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5, class: 'form-control w-50' %>
    </div>
    <div>
      <%= f.label "Categories:" %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: 'checkbox inline mx-2') {cb.check_box(class: 'checkbox mr-1') + cb.text.capitalize} %>
      <% end %>
    <div>
    <%= f.submit(options={class: "btn btn-outline-primary mt-3"}) %>
  <% end %>
</section>

app/views/posts/_post.html.erb
<article class='card bg-light m-3 post'>
  <div class='row no-gutters h-100'>
    <aside class='col-md-2 votes text-center'>
      <%= render 'shared/vote', obj: post %>
    </aside>

    <section class='col-md-10'>
      <header class='card-header'>
        <h5><%= truncate(post.title, length: 50) %></h5>
      </header>
  
      <main class='card-body'>
        <%= render 'posts/post_url', post: post, card: true %>
        <p class='card-text'>
          <%= simple_format(truncate(restrict_newlines(post.description, 5), length: 130)) %>
        </p>
      </main>
  
      <footer class='card-footer'>
        <%= render 'shared/creator_details', obj: post %>
        <nav class='btn-group mt-auto'>
          <%= button_to 'View', post_path(post), method: 'get', class: 'btn btn-sm btn-outline-secondary' %>
          <% if logged_in? && (current_user.admin? || (current_user == post.creator)) %>
            <%= button_to 'Edit', edit_post_path(post), method: 'get', class: 'btn btn-sm btn-outline-secondary border-left-0' %>
          <% end %>
        </nav>
      </footer>
    </section>
  </div>
</article>

app/views/posts/_post_url.html.erb
<% card ||= false %>
<% url_display = card ? truncate(fix_url(post.url), length: 28) : fix_url(post.url) %>

<p><%= link_to(body=url_display, url=fix_url(post.url)) %></p>

app/views/posts/edit.html.erb
<%= render 'shared/header', title: 'Edit this post' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/header', title: 'Posts' %>

<section class="row justify-content-center"> 
  <% @posts.each_with_index do |post, i| %>
    <%= render 'post', post: post %>
  <% end %>
</section>

app/views/posts/new.html.erb
<%= render 'shared/header', title: "Create a new post" %>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'shared/header', title: @post.title, obj: @post %>

<section class='container justify-content-center'>
  <p><%= simple_format(@post.description) %></p>

  <% if logged_in? %>
    <section class='w-50 pt-5'>
      <%= form_for [@post, @comment] do |f| %>
        <%= render 'shared/errors', obj: @comment %>
        <div class="form-group">
          <%= f.label :body, "Leave a comment" %>
          <%= f.text_area :body, rows: 3, class: "form-control" %>
        </div>
        <%= f.submit "Create comment", class: "btn btn-outline-primary btn-sm" %>
      <% end %>
    </section>
  <% end %>

  <section class='py-5'>
    <h5 class='pb-2'>Comments</h5>
    <% if @post.comments.empty? %>
      <p class="text-muted">There aren't any comments for this post.</p>
    <% else %>
      <% @post.reload.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    <% end %>
  </section>
</section>

app/views/posts/vote.js.erb
$total_votes = $('#<%= @post.class %>_<%= @post.slug %>_votes');
$total_votes.text(<%= @post.total_votes %>);
$upvote = $total_votes.siblings('.upvote');
$downvote = $total_votes.siblings('.downvote');

if (<%= @upvote %>) {
  $upvote.html('<i><i class="fas fa fa-arrow-up disabled"></i>');
  $downvote.html('<%= link_to(vote_post_path(@post, vote: false), method: 'post', remote: true) {|x| fa_icon 'arrow-down'} %>');
} else {
  $downvote.html('<i><i class="fas fa fa-arrow-down disabled"></i>');
  $upvote.html('<%= link_to(vote_post_path(@post, vote: true), method: 'post', remote: true) {|x| fa_icon 'arrow-up'} %>');
}

app/views/shared/_creator_details.html.erb
<% user_url = user_path(obj.creator.slug) %>
<% created_at = " #{display_datetime(obj.created_at)}" %>

<p><small class="text-muted"><%= link_to(obj.creator.username, user_url)%></small></p>
<p><small class="text-muted"><%= created_at %></small></p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <section class="alert alert-danger">
    <div class="container">
    <h5>Please fix the following errors:</h5>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  </section>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <div class="container">
      <%= flash[:notice] %>
    </div>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger">
    <div class="container">
      <%= flash[:error] %>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<% obj ||= nil %>
<% can_edit ||= nil %>

<% if obj.class == Post %>
  <% title = obj.title %>
  <% edit_url = edit_post_path(obj.slug)%>
  <% can_edit = logged_in? && (current_user.admin? || (current_user == obj.creator)) %>
<% elsif obj.class == User %>
  <% title = obj.username %>
  <% edit_url = edit_user_path(obj.slug)%>
  <% can_edit = (current_user == obj)%>
<% end %>

<%= render 'shared/nav' %>
<section class='jumbotron text-center'>
  <h1 class='jumbotron-heading'><%= title %></h1>

  <% if obj.class == Post %>
    <%= render 'post_url', post: obj %>
    <%= render 'shared/creator_details', obj: obj %>
  <% end %>

  <% if obj.class == User %>
    <p><%= obj.time_zone || Time.zone.name %></p> 
  <% end %>

  <% if can_edit %>
    <%= link_to 'Edit', edit_url %>
  <% end %>

</section>
<%= render 'shared/flash' %>

app/views/shared/_nav.html.erb
<!--Navbar-->
<nav class='navbar navbar-expand-sm navbar-dark bg-dark'>
  <!-- Navbar brand -->
  <%= link_to 'PostIt', root_path, class: 'navbar-brand' %>
    <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class='navbar-nav'>
      <li class='nav-item'>
        <%= link_to 'Posts', posts_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to 'Categories', categories_path, class: 'nav-link' %>
      </li>
      <% if logged_in? %>
        <li class='nav-item'>
          <%= link_to 'New Post', new_post_path, class: 'nav-link' %>
        </li>
        <% if current_user.admin? %>
          <li class='nav-item'>
            <%= link_to 'New Category', new_category_path, class: 'nav-link' %>
          </li>
        <% end %>
      <% end %>
    </ul>

    <ul class='navbar-nav flex-row ml-md-auto d-none d-md-flex'>
      <% if logged_in? %>
        <li class='nav-item'>
          <%= link_to 'Log Out', logout_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to 'Profile', user_path(current_user.slug), class: 'nav-link text-right' %>
        </li>
      <% else %>
        <li class='nav-item'>
          <%= link_to 'Register', register_path, class: 'nav-link' %>
        </li>
        <li class='nav-item'>
          <%= link_to 'Log In', login_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
</nav>

app/views/shared/_vote.html.erb
<% if obj.class == Post %>
  <% url_true = vote_post_path(obj, vote: true) %>
  <% url_false = vote_post_path(obj, vote: false) %>
<% elsif obj.class == Comment %>
  <% url_true = vote_post_comment_path(obj.post, obj, vote: true) %>
  <% url_false = vote_post_comment_path(obj.post, obj, vote: false) %>
<% end %>

<% obj_identifier = (obj.class == Post ? obj.slug : obj.id) %>

<span class='upvote'>
  <% if !current_user || obj.votes.where(user_id: current_user.id, vote: true).empty? %>
    <%= link_to url_true, method: 'post', remote: true do %>
      <%= fa_icon 'arrow-up' %>
    <% end %>
  <% else %>
    <%= fa_icon 'arrow-up', class: 'disabled' %>
  <% end %>
</span>
<div id='<%= obj.class %>_<%= obj_identifier %>_votes'><%= obj.total_votes %></div>
<span class='downvote'>
  <% if !current_user || obj.votes.where(user_id: current_user.id, vote: false).empty? %>
    <%= link_to url_false, method: 'post', remote: true do %>
      <%= fa_icon 'arrow-down' %>
    <% end %>
  <% else %>
    <%= fa_icon 'arrow-down', class: 'disabled' %>
  <% end %>
</span>

app/views/users/_form.html.erb
<div class='container'>
  <%= form_with(model: @user, local: true, html: {autocomplete: 'off'}) do |f| %>
    <%= render 'shared/errors', obj: @user %>
    <div class='form-group'>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control w-50' %>
    </div>
    <div class='form-group'>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control w-50' %>
    </div>
    <div class='form-group'>
      <%= f.label :time_zone %>
      <div>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>
      </div>
    </div>
    <%= f.submit(@user.new_record? ? "Register" : "Update Profile", class: "btn btn-outline-primary mt-3")%>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/header', title: "Edit Profile" %>
<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/header', title: "Register" %>
<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/header', title: @user.username, obj: @user %>

<section class='container'>
  <% number_of_posts = @user.posts.empty? ? 0 : @user.posts.size %>
  <% number_of_comments = @user.comments.empty? ? 0 : @user.comments.size %>
  
  <ul class='nav nav-tabs'>
    <li class='nav-item'>
      <%= link_to "Posts (#{number_of_posts})", user_path(@user), class: 'nav-link' %>
    </li>
    <li class='nav-item'>
      <%= link_to "Comments (#{number_of_comments})", user_path(@user, tab: 'comments'), class: 'nav-link' %>
    </li>
  </ul>
  
  <% if params[:tab].nil? %>
    <% if @user.posts.empty? %>
      <p class="text-muted">There aren't any posts for this user.</p>
    <% else %>
      <% @user.posts.each do |post| %>
        <%= render 'posts/post', post: post %>
      <% end %>
    <% end %>
  <% elsif params[:tab] == 'comments' %>
    <% if @user.comments.empty? %>
      <p class="text-muted">There aren't any comments for this user.</p>
    <% else %>
      <% @user.comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment, show_post: true %>
      <% end %>
    <% end %>
  <% end %>
</section>